/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "user";

export interface Acknowledgments {
  content: Generated<string>;
  content_en: string | null;
  created_at: Generated<Timestamp | null>;
  id: Generated<number>;
  updated_at: Generated<Timestamp | null>;
}

export interface AmirWritings {
  content: string;
  created_at: Generated<Timestamp | null>;
  display_order: Generated<number | null>;
  id: Generated<number>;
  image_url: string | null;
  title: string;
  updated_at: Generated<Timestamp | null>;
}

export interface BiographyContent {
  content: string;
  content_en: string | null;
  created_at: Generated<Timestamp>;
  display_order: number;
  id: Generated<number>;
  images: Generated<Json | null>;
  section_title: string;
  section_title_en: string | null;
  updated_at: Generated<Timestamp>;
}

export interface GuestbookMessages {
  created_at: Generated<Timestamp | null>;
  id: Generated<number>;
  message: string;
  relationship: string | null;
  updated_at: Generated<Timestamp | null>;
  visitor_name: string;
}

export interface Images {
  created_at: Generated<Timestamp>;
  description: string | null;
  description_en: string | null;
  id: Generated<number>;
  image_data: string;
  mime_type: string;
  name: string;
  updated_at: Generated<Timestamp | null>;
}

export interface Memories {
  author: string | null;
  author_en: string | null;
  content: string | null;
  content_en: string | null;
  created_at: Generated<Timestamp | null>;
  description: string | null;
  id: Generated<number>;
  image_id: number | null;
  source: string | null;
  title_en: string | null;
  topic: string | null;
  type: string;
  updated_at: Generated<Timestamp | null>;
  video_id: number | null;
}

export interface OauthAccounts {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  provider: string;
  provider_email: string;
  provider_user_id: string;
  updated_at: Generated<Timestamp>;
  user_id: number;
}

export interface OauthStates {
  code_verifier: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<number>;
  provider: string;
  redirect_url: string;
  state: string;
}

export interface ProfileInfo {
  birth_date: Timestamp;
  created_at: Generated<Timestamp | null>;
  death_date: Timestamp;
  id: Generated<number>;
  name: string;
  name_en: string | null;
  photo_url: string | null;
  quote: string | null;
  quote_en: string | null;
  short_biography: string | null;
  short_biography_en: string | null;
  updated_at: Generated<Timestamp | null>;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  last_accessed: Generated<Timestamp>;
  user_id: number;
}

export interface Tributes {
  author_name: string;
  content: string;
  created_at: Generated<Timestamp | null>;
  display_order: Generated<number | null>;
  id: Generated<number>;
  is_featured: Generated<boolean | null>;
  relationship: string;
  updated_at: Generated<Timestamp | null>;
}

export interface UserPasswords {
  created_at: Generated<Timestamp>;
  password_hash: string;
  updated_at: Generated<Timestamp>;
  user_id: number;
}

export interface Users {
  avatar_url: string | null;
  created_at: Generated<Timestamp>;
  display_name: string;
  email: string;
  id: Generated<number>;
  role: Generated<UserRole>;
  updated_at: Generated<Timestamp>;
}

export interface Videos {
  created_at: Generated<Timestamp | null>;
  description: string | null;
  id: Generated<number>;
  mime_type: string;
  name: string;
  video_data: string;
}

export interface DB {
  acknowledgments: Acknowledgments;
  amir_writings: AmirWritings;
  biography_content: BiographyContent;
  guestbook_messages: GuestbookMessages;
  images: Images;
  memories: Memories;
  oauth_accounts: OauthAccounts;
  oauth_states: OauthStates;
  profile_info: ProfileInfo;
  sessions: Sessions;
  tributes: Tributes;
  user_passwords: UserPasswords;
  users: Users;
  videos: Videos;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin","user"];